#!/bin/sh
set -x -eo pipefail

###
# Dependencies
###

apk add --no-cache curl \
                   python3=${PYTHON3_VERSION} \
                   py3-boto3==${BOTO3_VERSION}

###
# Installation
###

curl -sSLo /tmp/aws-nuke-${AWS_NUKE_VERSION}-linux-amd64.tar.gz \
    https://github.com/rebuy-de/aws-nuke/releases/download/${AWS_NUKE_VERSION}/aws-nuke-${AWS_NUKE_VERSION}-linux-amd64.tar.gz
tar --directory /tmp -xzf /tmp/aws-nuke-${AWS_NUKE_VERSION}-linux-amd64.tar.gz aws-nuke-${AWS_NUKE_VERSION}-linux-amd64
mv /tmp/aws-nuke-${AWS_NUKE_VERSION}-linux-amd64 /usr/local/bin/aws-nuke
chmod +x /usr/local/bin/aws-nuke

###
# Create default AWS resources python script
###

mv /resources/create_aws_default_resources.py /usr/local/bin/create_aws_default_resources
chmod +x /usr/local/bin/create_aws_default_resources

###
# Create entrypoint
###

mv /resources/entrypoint.sh /usr/local/bin/entrypoint.sh
chmod +x /usr/local/bin/entrypoint.sh

###
# Cleaning
###

apk del curl

###
# Check
###

aws-nuke version

###
# CIS Hardening
###

chmod 0600 /etc/shadow

touch /etc/login.defs
chmod 0444 /etc/login.defs
